name: Test on GKE
on:
  push: {}


jobs:
  run-integrationtest:
    runs-on: ubuntu-latest

    steps:
    # Setup gcloud CLI
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.7.0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}